import pandas as pd
import pandas_ta as ta
import os
import glob

class MarketFeatureEngineer:
    def __init__(self, input_dir: str, output_dir: str):
        # Initialize input and output directories
        self.input_dir = input_dir
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        # Ensure Date is a datetime object and sorted
        df['Date'] = pd.to_datetime(df['Date'])
        df.sort_values('Date', inplace=True)

        # 1. Trend Indicators (Swing Trading)
        df['SMA_20'] = ta.sma(df['Close'], length=20)
        df['EMA_9'] = ta.ema(df['Close'], length=9)

        # 2. Momentum Indicators
        df['RSI_14'] = ta.rsi(df['Close'], length=14)
        df.ta.macd(close='Close', fast=12, slow=26, signal=9, append=True)

        # 3. Volatility Indicators (Intraday/Stoploss)
        df['ATR_14'] = ta.atr(df['High'], df['Low'], df['Close'], length=14)

        # 4. Target Variable for ML (1 if price goes up tomorrow, else 0)
        df['Target_Next_Day'] = (df['Close'].shift(-1) > df['Close']).astype(float)

        # Drop NaN values generated by indicator rolling windows
        df.dropna(inplace=True)

        return df

    def run(self):
        file_pattern = os.path.join(self.input_dir, "*_raw.csv")
        file_list = glob.glob(file_pattern)
        
        print(f"=== Starting Feature Engineering: {len(file_list)} files ===")
        
        for file_path in file_list:
            file_name = os.path.basename(file_path)
            ticker = file_name.replace("_raw.csv", "")
            
            print(f"[*] Engineering features for: {ticker}...")
            df_raw = pd.read_csv(file_path)
            
            df_processed = self.generate_indicators(df_raw)
            
            save_path = os.path.join(self.output_dir, f"{ticker}_features.csv")
            df_processed.to_csv(save_path, index=False)
            print(f"[v] Processed {len(df_processed)} valid rows.")
            
        print("=== Process Completed ===")

if __name__ == "__main__":
    input_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../data/raw"))
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../data/processed"))
    
    engineer = MarketFeatureEngineer(input_dir=input_path, output_dir=output_path)
    engineer.run()